# Generated by Django 5.0.6 on 2024-06-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('department1', 'Department 1'), ('department2', 'Department 2'), ('department3', 'Department 3')], max_length=100),
        ),
    ]
