# Generated by Django 5.0.6 on 2024-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dropdown_field',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
