# Generated by Django 5.0.6 on 2024-06-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_task_dropdown_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dropdown_field',
            new_name='time',
        ),
    ]
