# Generated by Django 5.0.6 on 2024-06-26 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_task_approved_alter_task_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Task1',
        ),
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('6:00 AM', '6:00AM'), ('7:00 AM', '7:00AM'), ('8:00 AM', '8:00AM'), ('9:00 AM', '9:00AM'), ('10:00 AM', '10:00AM'), ('11:00 AM', '11:00AM'), ('12:00 PM', '12:00PM'), ('1:00 PM', '1:00PM'), ('2:00 PM', '2:00PM'), ('3:00 PM', '3:00PM'), ('4:00 PM', '4:00PM'), ('5:00 PM', '5:00PM'), ('6:00 PM', '6:00PM'), ('7:00 PM', '7:00PM'), ('8:00 PM', '8:00PM'), ('9:00 PM', '9:00PM')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('6:00 AM', '6:00AM'), ('7:00 AM', '7:00AM'), ('8:00 AM', '8:00AM'), ('9:00 AM', '9:00AM'), ('10:00 AM', '10:00AM'), ('11:00 AM', '11:00AM'), ('12:00 PM', '12:00PM'), ('1:00 PM', '1:00PM'), ('2:00 PM', '2:00PM'), ('3:00 PM', '3:00PM'), ('4:00 PM', '4:00PM'), ('5:00 PM', '5:00PM'), ('6:00 PM', '6:00PM'), ('7:00 PM', '7:00PM'), ('8:00 PM', '8:00PM'), ('9:00 PM', '9:00PM')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
